# -*- Makefile -*-
EMACS    = emacs
SITEFLAG = --no-site-file

# Xemacs users will probably want the following settings.
#EMACS    = emacs
#SITEFLAG = -no-site-file

# Installation options
# PREFIX is only used here.
PREFIX   = /usr/local
ELISPDIR = $(PREFIX)/share/emacs/site-lisp/emacs-wiki
INFODIR  = $(PREFIX)/info

# Command to use to install the Info dir entry
INSTALLINFO = install-info --info-dir=$(INFODIR)

# Useful only for the maintainer
VERSION  = 2.70
