(defun color-theme-mistyday ()
  "Color theme by K.C. Hari Kumar, created 2001-06-13.
Black on mistyrose.  Includes CUA, calendar, diary, font-latex and 
font-lock.  Uses backgrounds on some font-lock faces."
  (interactive)
  (color-theme-install
   '(color-theme-mistyday
     ((background-color . "mistyrose")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "deep pink")
      (foreground-color . "Black")
      (mouse-color . "black"))
     ((goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . bold)
      (goto-address-url-mouse-face . highlight)
      (list-matching-lines-face . bold)
      (paren-match-face . paren-face-match)
      (paren-mismatch-face . paren-face-mismatch)
      (paren-no-match-face . paren-face-no-match))
    (default ((t (nil))))
    (CUA-global-mark-face ((t (:background "cyan" :foreground "black"))))
    (CUA-rectangle-face ((t (:background "maroon" :foreground "white"))))
    (CUA-rectangle-noselect-face ((t (:background "dimgray" :foreground "white"))))
    (bold ((t (:bold t))))
    (bold-italic ((t (:italic t :bold t))))
    (calendar-today-face ((t (:underline t :background "Spring Green" :foreground "Brown"))))
    (custom-button-face ((t (:background "dark slate grey" :foreground "azure"))))
    (custom-documentation-face ((t (:background "white" :foreground "blue"))))
    (diary-face ((t (:background "navy" :foreground "yellow"))))
    (font-latex-bold-face ((t (:bold t :foreground "DarkOliveGreen"))))
    (font-latex-italic-face ((t (:italic t :foreground "DarkOliveGreen"))))
    (font-latex-math-face ((t (:foreground "navy"))))
    (font-latex-sedate-face ((t (:foreground "DimGray"))))
    (font-latex-string-face ((t (nil))))
    (font-latex-warning-face ((t (nil))))
    (font-lock-builtin-face ((t (:background "DarkTurquoise" :foreground "Navy"))))
    (font-lock-comment-face ((t (:italic t :foreground "royal blue"))))
    (font-lock-constant-face ((t (:background "pale green" :foreground "dark slate blue"))))
    (font-lock-doc-string-face ((t (:background "medium aquamarine" :foreground "deep pink"))))
    (font-lock-function-name-face ((t (:background "SpringGreen" :foreground "MidnightBlue"))))
    (font-lock-keyword-face ((t (:foreground "dark magenta"))))
    (font-lock-preprocessor-face ((t (:background "pale green" :foreground "dark slate blue"))))
    (font-lock-reference-face ((t (:background "DarkTurquoise" :foreground "Navy"))))
    (font-lock-string-face ((t (:background "medium aquamarine" :foreground "deep pink"))))
    (font-lock-type-face ((t (:background "steel blue" :foreground "khaki"))))
    (font-lock-variable-name-face ((t (:background "thistle" :foreground "orange red"))))
    (font-lock-warning-face ((t (:background "LemonChiffon" :foreground "Red"))))
    (highlight ((t (:background "dark slate grey" :foreground "light cyan"))))
    (holiday-face ((t (:background "orangered" :foreground "lightyellow"))))
    (ido-first-match-face ((t (:bold t))))
    (ido-only-match-face ((t (:foreground "ForestGreen"))))
    (ido-subdir-face ((t (:foreground "red"))))
    (italic ((t (:italic t))))
    (isearch ((t (:background "sienna" :foreground "light cyan"))))
    (modeline ((t (:background "Royalblue4" :foreground "lawn green"))))
    (modeline-buffer-id ((t (:background "Royalblue4" :foreground "lawn green"))))
    (modeline-mousable ((t (:background "Royalblue4" :foreground "lawn green"))))
    (modeline-mousable-minor-mode ((t (:background "Royalblue4" :foreground "lawn green"))))
    (paren-face-match ((t (:background "turquoise"))))
    (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
    (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
    (primary-selection ((t (:background "sienna" :foreground "light cyan"))))
    (region ((t (:background "sienna" :foreground "light cyan"))))
    (secondary-selection ((t (:background "forest green" :foreground "white smoke"))))
    (underline ((t (:underline t))))
    (zmacs-region ((t (:background "sienna" :foreground "light cyan")))))))

(provide 'color-theme-mistyday)
