(defun color-theme-aalto-dark ()
  "Color theme by Jari Aalto, created 2001-03-08.
White on Deep Sky Blue 3.
Used for Unix Exceed on a Nokia446Xpro monitor.
Includes font-lock, info, and message."
  (interactive)
  (color-theme-install
   '(color-theme-aalto-dark
     ((background-color . "DeepSkyBlue3")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "yellow")
      (foreground-color . "white")
      (mouse-color . "black"))
     ((ispell-highlight-face . highlight)
      (list-matching-lines-face . bold)
      (tinyreplace-:face . highlight)
      (view-highlight-face . highlight))
    (default ((t (nil))))
    (bold ((t (:bold t :background "blue3" :foreground "white"))))
    (bold-italic ((t (:italic t :bold t :foreground "blue3"))))
    (calendar-today-face ((t (:underline t))))
    (diary-face ((t (:foreground "red"))))
    (font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
    (font-lock-comment-face ((t (:foreground "OrangeRed"))))
    (font-lock-constant-face ((t (:foreground "Aquamarine"))))
    (font-lock-function-name-face ((t (:foreground "LightSkyBlue"))))
    (font-lock-keyword-face ((t (:foreground "Cyan"))))
    (font-lock-string-face ((t (:foreground "LightSalmon"))))
    (font-lock-type-face ((t (:foreground "PaleGreen"))))
    (font-lock-variable-name-face ((t (:foreground "LightGoldenrod"))))
    (font-lock-warning-face ((t (:bold t :foreground "Pink"))))
    (highlight ((t (:background "blue3" :foreground "white"))))
    (holiday-face ((t (:background "pink"))))
    (info-menu-5 ((t (:underline t))))
    (info-node ((t (:italic t :bold t))))
    (info-xref ((t (:bold t))))
    (italic ((t (:italic t :background "gray"))))
    (message-cited-text-face ((t (:foreground "red"))))
    (message-header-cc-face ((t (:bold t :foreground "green4"))))
    (message-header-name-face ((t (:foreground "DarkGreen"))))
    (message-header-newsgroups-face ((t (:italic t :bold t :foreground "yellow"))))
    (message-header-other-face ((t (:foreground "#b00000"))))
    (message-header-subject-face ((t (:foreground "green3"))))
    (message-header-to-face ((t (:bold t :foreground "green2"))))
    (message-header-xheader-face ((t (:foreground "blue"))))
    (message-mml-face ((t (:foreground "ForestGreen"))))
    (message-separator-face ((t (:foreground "blue3"))))
    (modeline ((t (:background "DeepSkyBlue3" :foreground "white" :inverse-video t))))
    (modeline-buffer-id ((t (:background "DeepSkyBlue3" :foreground "white" :inverse-video t))))
    (modeline-mousable ((t (:background "DeepSkyBlue3" :foreground "white" :inverse-video t))))
    (modeline-mousable-minor-mode ((t (:background "DeepSkyBlue3" :foreground "white" :inverse-video t))))
    (region ((t (:background "gray"))))
    (secondary-selection ((t (:background "darkslateblue"))))
    (show-paren-match-face ((t (:background "turquoise"))))
    (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
    (underline ((t (:underline t)))))))

(provide 'color-theme-aalto-dark)
