(defun color-theme-blippblopp ()
  "Color theme by Thomas Sicheritz-Ponten, created 2001-03-12.
Used by researchers at Uppsala University and the Center for Biological
Sequence Analysis at the Technical University of Denmark. (As some of my
swedish friends couldn't pronounce Sicheritz - they choose to transform
it to something more \"swedish\": Blippblopp :-)
Includes font-lock and message."
  (interactive)
  (color-theme-install
   '(color-theme-blippblopp
     ((background-color . "white")
      (background-mode . light)
      (background-toolbar-color . "#cf3ccf3ccf3c")
      (border-color . "#000000000000")
      (bottom-toolbar-shadow-color . "#79e77df779e7")
      (cursor-color . "Red3")
      (foreground-color . "black")
      (mouse-color . "black")
      (top-toolbar-shadow-color . "#fffffbeeffff")
      (viper-saved-cursor-color-in-replace-mode . "Red3"))
     ((ispell-highlight-face . highlight))
    (default ((t (:background "white" :foreground "black"))))
    (blue ((t (:foreground "blue"))))
    (bold ((t (:bold t))))
    (bold-italic ((t (:italic t :bold t))))
    (excerpt ((t (:italic t))))
    (ff-paths-non-existant-file-face ((t (:bold t :foreground "NavyBlue"))))
    (fg:black ((t (:foreground "black"))))
    (fixed ((t (:bold t))))
    (font-lock-builtin-face ((t (:foreground "red3"))))
    (font-lock-comment-face ((t (:foreground "orange"))))
    (font-lock-constant-face ((t (:foreground "red3"))))
    (font-lock-doc-string-face ((t (:foreground "darkgreen"))))
    (font-lock-exit-face ((t (:foreground "green"))))
    (font-lock-function-name-face ((t (:bold t :foreground "red"))))
    (font-lock-keyword-face ((t (:bold t :foreground "steelblue"))))
    (font-lock-preprocessor-face ((t (:foreground "blue3"))))
    (font-lock-reference-face ((t (:foreground "red3"))))
    (font-lock-string-face ((t (:foreground "green4"))))
    (font-lock-type-face ((t (:bold t :foreground "blue"))))
    (font-lock-variable-name-face ((t (:foreground "black"))))
    (font-lock-warning-face ((t (:bold t :foreground "Red"))))
    (green ((t (:foreground "green"))))
    (message-cited-text-face ((t (:foreground "red"))))
    (message-header-cc-face ((t (:foreground "MidnightBlue"))))
    (message-header-name-face ((t (:foreground "cornflower blue"))))
    (message-header-newsgroups-face ((t (:italic t :bold t :foreground "blue4"))))
    (message-header-other-face ((t (:foreground "steel blue"))))
    (message-header-subject-face ((t (:bold t :foreground "navy blue"))))
    (message-header-to-face ((t (:bold t :foreground "MidnightBlue"))))
    (message-header-xheader-face ((t (:foreground "blue"))))
    (message-mml-face ((t (:foreground "ForestGreen"))))
    (message-separator-face ((t (:foreground "brown"))))
    (modeline ((t (:background "dimgray" :foreground "lemonchiffon"))))
    (modeline-buffer-id ((t (:background "dimgray" :foreground "green3"))))
    (modeline-mousable ((t (:background "dimgray" :foreground "orange"))))
    (modeline-mousable-minor-mode ((t (:background "dimgray" :foreground "blue4"))))
    (primary-selection ((t (:background "gray65"))))
    (red ((t (:foreground "red"))))
    (region ((t (:background "gray65"))))
    (secondary-selection ((t (:background "paleturquoise"))))
    (show-paren-match-face ((t (:background "turquoise"))))
    (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
    (text-cursor ((t (:background "Red3" :foreground "white"))))
    (toolbar ((t (:background "Gray80"))))
    (underline ((t (:underline t))))
    (vcursor ((t (:underline t :background "cyan" :foreground "blue"))))
    (vertical-divider ((t (:background "Gray80"))))
    (xref-keyword-face ((t (:foreground "blue"))))
    (xref-list-pilot-face ((t (:foreground "navy"))))
    (xref-list-symbol-face ((t (:foreground "navy"))))
    (yellow ((t (:foreground "yellow"))))
    (zmacs-region ((t (:background "gray65")))))))

(provide 'color-theme-blippblopp)
