(defun color-theme-classic ()
  "Color theme by Frederic Giroud, created 2001-01-18.
AntiqueWhite on darkslategrey scheme.  Based on Gnome 2, with my favorit
color foreground-color and fontlock color."
  (interactive)
  (color-theme-blue-gnus)
  (let ((color-theme-cumulative t))
    (color-theme-install
     '(color-theme-classic
       ((foreground-color . "AntiqueWhite")
	(background-color . "darkslategrey")
	(mouse-color . "Grey")
	(cursor-color . "Red")
	(border-color . "black")
	(background-mode . dark))
       ((apropos-keybinding-face . underline)
	(apropos-label-face . (face italic mouse-face highlight))
	(apropos-match-face . secondary-selection)
	(apropos-property-face . bold-italic)
	(apropos-symbol-face . info-xref)
	(goto-address-mail-face . message-header-to-face)
	(goto-address-mail-mouse-face . secondary-selection)
	(goto-address-url-face . info-xref)
	(goto-address-url-mouse-face . highlight)
	(list-matching-lines-face . bold)
	(view-highlight-face . highlight))
       (default ((t (nil))))
       (bold ((t (:bold t))))
       (bold-italic ((t (:italic t :bold t :foreground "beige"))))
       (calendar-today-face ((t (:underline t))))
       (cperl-array-face ((t (:foreground "Yellow"))))
       (cperl-hash-face ((t (:foreground "White"))))
       (cperl-nonoverridable-face ((t (:foreground "SkyBlue"))))
       (custom-button-face ((t (:underline t :foreground "MediumSlateBlue"))))
       (custom-documentation-face ((t (:foreground "Grey"))))
       (custom-group-tag-face ((t (:foreground "MediumAquamarine"))))
       (custom-state-face ((t (:foreground "LightSalmon"))))
       (custom-variable-tag-face ((t (:foreground "Aquamarine"))))
       (diary-face ((t (:foreground "IndianRed"))))
       (erc-action-face ((t (:bold t))))
       (erc-bold-face ((t (:bold t))))
       (erc-default-face ((t (nil))))
       (erc-direct-msg-face ((t (:foreground "LightSalmon"))))
       (erc-error-face ((t (:bold t :foreground "IndianRed"))))
       (erc-input-face ((t (:foreground "Beige"))))
       (erc-inverse-face ((t (:background "wheat" :foreground "darkslategrey"))))
       (erc-notice-face ((t (:foreground "MediumAquamarine"))))
       (erc-pal-face ((t (:foreground "pale green"))))
       (erc-prompt-face ((t (:foreground "MediumAquamarine"))))
       (erc-underline-face ((t (:underline t))))
       (eshell-ls-archive-face ((t (:bold t :foreground "IndianRed"))))
       (eshell-ls-backup-face ((t (:foreground "Grey"))))
       (eshell-ls-clutter-face ((t (:foreground "DimGray"))))
       (eshell-ls-directory-face ((t (:bold t :foreground "MediumSlateBlue"))))
       (eshell-ls-executable-face ((t (:foreground "Coral"))))
       (eshell-ls-missing-face ((t (:foreground "black"))))
       (eshell-ls-picture-face ((t (:foreground "Violet"))))
       (eshell-ls-product-face ((t (:foreground "LightSalmon"))))
       (eshell-ls-readonly-face ((t (:foreground "Aquamarine"))))
       (eshell-ls-special-face ((t (:foreground "Gold"))))
       (eshell-ls-symlink-face ((t (:foreground "White"))))
       (eshell-ls-unreadable-face ((t (:foreground "DimGray"))))
       (eshell-prompt-face ((t (:foreground "MediumAquamarine"))))
       (font-lock-builtin-face ((t (:bold t :foreground "PaleGreen"))))
       (font-lock-comment-face ((t (:foreground "tomato3"))))
       (font-lock-constant-face ((t (:foreground "Aquamarine"))))
       (font-lock-doc-string-face ((t (:foreground "LightSalmon3"))))
       (font-lock-function-name-face ((t (:foreground "SteelBlue1"))))
       (font-lock-keyword-face ((t (:foreground "cyan1"))))
       (font-lock-reference-face ((t (:foreground "LightSalmon2"))))
       (font-lock-string-face ((t (:foreground "LightSalmon3"))))
       (font-lock-type-face ((t (:foreground "PaleGreen3"))))
       (font-lock-variable-name-face ((t (:foreground "khaki1"))))
       (font-lock-warning-face ((t (:bold t :foreground "IndianRed"))))
       (font-lock-preprocessor-face ((t (:foreground "SkyBlue3"))))
       (widget-field-face ((t (:background "DarkCyan"))))
       (custom-group-tag-face ((t(:foreground "brown" :underline t))))
       (custom-state-face ((t (:foreground "khaki"))))
       (highlight ((t (:background "PaleGreen" :foreground "DarkGreen"))))
       (highline-face ((t (:background "SeaGreen"))))
       (holiday-face ((t (:background "DimGray"))))
       (info-menu-5 ((t (:underline t))))
       (info-node ((t (:underline t :bold t :foreground "DodgerBlue1"))))
       (info-xref ((t (:underline t :foreground "DodgerBlue1"))))
       (isearch ((t (:foreground "red" :background "CornflowerBlue"))))
       (italic ((t (:italic t))))
       (modeline ((t (:background "LightSlateGray" :foreground "AntiqueWhite"))))
       (modeline-buffer-id ((t (:background "LightSlateGray" :foreground "DarkBlue"))))
       (modeline-mousable ((t (:background "LightSlateGray" :foreground "firebrick"))))
       (modeline-mousable-minor-mode ((t (:background "LightSlateGray" :foreground "wheat"))))
       (region ((t (:background "dark cyan" :foreground "cyan"))))
       (secondary-selection ((t (:background "Aquamarine" :foreground "SlateBlue"))))
       (show-paren-match-face ((t (:background "Aquamarine" :foreground "SlateBlue"))))
       (show-paren-mismatch-face ((t (:background "Red" :foreground "White"))))
       (underline ((t (:underline t))))
       (widget-field-face ((t (:foreground "LightBlue"))))
       (widget-inactive-face ((t (:foreground "DimGray"))))
       (widget-single-line-field-face ((t (:foreground "LightBlue"))))
       (woman-bold-face ((t (:bold t))))
       (woman-italic-face ((t (:foreground "beige"))))
       (woman-unknown-face ((t (:foreground "LightSalmon"))))))))

(provide 'color-theme-classic)
