(defun color-theme-goldenrod ()
  "Brown color theme.  It's ugly, but it's different.
Supports standard, font-lock and info faces."
  (interactive)
  (color-theme-install
   '(color-theme-goldenrod
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "light goldenrod")
      (foreground-color . "dark goldenrod")
      (mouse-color . "goldenrod"))
     ((goto-address-mail-face . info-xref)
      (list-matching-lines-face . bold)
      (view-highlight-face . highlight))
    (default ((t (nil))))
    (bold ((t (:bold t))))
    (bold-italic ((t (:italic t :bold t))))
    (font-lock-builtin-face ((t (:foreground "pale goldenrod"))))
    (font-lock-comment-face ((t (:foreground "firebrick"))))
    (font-lock-constant-face ((t (:foreground "orange" :bold t))))
    (font-lock-function-name-face ((t (:foreground "khaki" :bold t :background "sienna"))))
    (font-lock-keyword-face ((t (:foreground "wheat" :bold t))))
    (font-lock-string-face ((t (:foreground "gold"))))
    (font-lock-type-face ((t (:foreground "dark khaki" :bold t))))
    (font-lock-variable-name-face ((t (:foreground "khaki" :background "sienna"))))
    (font-lock-warning-face ((t (:bold t :foreground "orange red" :background "pale goldenrod"))))
    (highlight ((t (:background "gold"))))
    (info-menu-5 ((t (:underline t))))
    (info-node ((t (:bold t))))
    (info-xref ((t (:bold t :foreground "pale goldenrod"))))
    (italic ((t (:italic t :foreground "midnight blue"))))
    (modeline ((t (:background "saddle brown" :foreground "wheat" :inverse-video t))))
    (modeline-buffer-id ((t (:background "saddle brown" :foreground "wheat" :inverse-video t))))
    (modeline-mousable ((t (:background "saddle brown" :foreground "wheat" :inverse-video t))))
    (modeline-mousable-minor-mode ((t (:background "saddle brown" :foreground "wheat" :inverse-video t))))
    (region ((t (:background "dark olive green"))))
    (secondary-selection ((t (:background "dark green"))))
    (underline ((t (:underline t)))))))

(provide 'color-theme-goldenrod)
