(defun color-theme-loyola ()
  "Color theme by Loyola, created 2000-12-11.
White Smoke on Dodger Blue 4."
  (interactive)
  (color-theme-install
   '(color-theme-loyola
     ((background-color . "DodgerBlue4")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "DarkGoldenrod1")
      (foreground-color . "white smoke")
      (mouse-color . "black"))
     ((list-matching-lines-face . bold))
    (default ((t (nil))))
    (bold ((t (:bold t))))
    (bold-italic ((t (:italic t :bold t))))
    (cperl-array-face ((t (:bold t :foreground "wheat"))))
    (cperl-hash-face ((t (:bold t :foreground "chartreuse"))))
    (font-lock-builtin-face ((t (:bold t :foreground "wheat"))))
    (font-lock-comment-face ((t (:bold t :foreground "gray72"))))
    (font-lock-constant-face ((t (:bold t :foreground "cyan3"))))
    (font-lock-doc-string-face ((t (:foreground "#008000"))))
    (font-lock-function-name-face ((t (:bold t :foreground "chartreuse"))))
    (font-lock-keyword-face ((t (:bold t :foreground "gold1"))))
    (font-lock-other-emphasized-face ((t (:bold t :foreground "gold1"))))
    (font-lock-other-type-face ((t (:bold t :foreground "gold1"))))
    (font-lock-preprocessor-face ((t (:foreground "#800080"))))
    (font-lock-string-face ((t (:foreground "plum"))))
    (font-lock-type-face ((t (:bold t :foreground "gold1"))))
    (font-lock-variable-name-face ((t (:foreground "light yellow"))))
    (font-lock-warning-face ((t (:foreground "plum"))))
    (highlight ((t (:background "gray91" :foreground "firebrick"))))
    (italic ((t (:italic t))))
    (modeline ((t (:background "white" :foreground "OrangeRed3" :inverse-video t))))
    (modeline-buffer-id ((t (:background "white" :foreground "OrangeRed3" :inverse-video t))))
    (modeline-mousable ((t (:background "white" :foreground "OrangeRed3" :inverse-video t))))
    (modeline-mousable-minor-mode ((t (:background "white" :foreground "OrangeRed3" :inverse-video t))))
    (my-tab-face ((t (:background "SlateBlue1"))))
    (p4-diff-del-face ((t (:bold t :foreground "salmon"))))
    (region ((t (:background "gray91" :foreground "DodgerBlue4"))))
    (secondary-selection ((t (:background "gray91" :foreground "sienna3"))))
    (show-paren-match-face ((t (:background "cyan3" :foreground "blue"))))
    (show-paren-mismatch-face ((t (:background "red" :foreground "blue"))))
    (underline ((t (:underline t))))
    (widget-button-face ((t (:bold t))))
    (widget-button-pressed-face ((t (:foreground "red"))))
    (widget-documentation-face ((t (:foreground "dark green"))))
    (widget-field-face ((t (:background "gray85"))))
    (widget-inactive-face ((t (:foreground "dim gray"))))
    (widget-single-line-field-face ((t (:background "gray85")))))))

(provide 'color-theme-loyola)
