#!/bin/sh

cd

for shortcut in \
    .eid .as-bindings.el .as-gtd.el .el-get .as-custom .msf-abbrevs
do
    if [ -L $shortcut ]; then
        rm $shortcut
    fi
done

# Put this last as it's most likely to fail.
emk
