#!/bin/bash

GCONFTOOL=gconftool-2

if ! which $GCONFTOOL >/dev/null 2>&1; then
    echo "WARNING: can't find $GCONFTOOL; url-handlers will not be set" >&2
else
    $GCONFTOOL -s /desktop/gnome/url-handlers/annotation/command \
               -t string 'org-annotation-helper %s'
    $GCONFTOOL -s /desktop/gnome/url-handlers/annotation/enabled -t bool yes

    $GCONFTOOL -s /desktop/gnome/url-handlers/remember/command \
               -t string 'org-annotation-helper %s'
    $GCONFTOOL -s /desktop/gnome/url-handlers/remember/enabled -t bool yes

    $GCONFTOOL -s /desktop/gnome/url-handlers/org-protocol/command \
               -t string 'quick-emacs %s'
    $GCONFTOOL -s /desktop/gnome/url-handlers/org-protocol/enabled -t bool yes
fi

# Ensure ~/.local/share/applications/mimeapps.list has an appropriate
# entry for handling org-protocol:// links.
if ! xdg-mime query default x-scheme-handler/org-protocol | grep -q emacs; then
    xdg-mime default quick-emacs.desktop x-scheme-handler/org-protocol
fi

# This isn't needed; it's for system-wide .desktop files
#sudo update-desktop-database
