#!/bin/bash

GCONFTOOL=gconftool-2

if ! which $GCONFTOOL >/dev/null 2>&1; then
    echo "WARNING: can't find $GCONFTOOL; url-handlers will not be set" >&2
else
    $GCONFTOOL -s /desktop/gnome/url-handlers/org-protocol/command \
               -t string 'quick-emacs %s'
    $GCONFTOOL -s /desktop/gnome/url-handlers/org-protocol/enabled -t bool yes
fi

# Ensure ~/.local/share/applications/mimeapps.list has an appropriate
# entry for handling org-protocol:// links.
xdg-mime default quick-emacs.desktop x-scheme-handler/org-protocol

# This should succeed even without running the above, but it's worth checking
# anyway.
if ! xdg-mime query default x-scheme-handler/org-protocol | grep -q emacs; then
    echo "WARNING: xdg-mime failed to install handler for org-protocol:// !" >&2
fi

# This isn't needed; it's for system-wide .desktop files
#sudo update-desktop-database
