(setq indent-tabs-mode t)
(custom-set-variables
 '(cperl-auto-newline-after-colon t)
 '(fast-lock-minimum-size 4096)
 '(cperl-under-as-char nil)
 '(iswitchb-case nil)
 '(lazy-lock-defer-on-scrolling t)
 '(scroll-margin -1 t)
 '(scroll-step 2)
 '(show-paren-delay 0)
 '(scroll-conservatively 20 t)
 '(lazy-lock-stealth-time 15)
 '(scroll-preserve-screen-position t t)
 '(lazy-lock-minimum-size 4096)
 '(iswitchb-buffer-ignore (quote ("^[* ]")))
 '(show-paren-mode t nil (paren))
 '(cperl-electric-keywords t)
 '(font-lock-support-mode (quote lazy-lock-mode))
 '(cperl-electric-parens-string "{}()")
 '(mouse-yank-at-point t)
 '(cperl-electric-linefeed t)
 '(cperl-invalid-face (quote (quote default)))
 '(diff-switches "-u" t)
 '(lazy-lock-defer-time 0.5)
 '(cperl-electric-parens t)
 '(lazy-lock-stealth-verbose t)
 '(indent-tabs-mode nil)
 '(mwheel-follow-mouse t)
 '(show-paren-ring-bell-on-mismatch nil)
 '(mwheel-scroll-amount (quote (5 1 nil)))
 '(cperl-lazy-help-time 2)
 '(cperl-auto-newline nil)
 '(global-font-lock-mode t nil (font-lock)))
(custom-set-faces
 '(font-lock-comment-face ((((class color) (background dark)) (:foreground "aquamarine"))))
 '(underline ((t (:underline t :foreground "Yellow"))))
 '(cperl-array-face ((((class color) (background dark)) (:bold t :foreground "yellow"))))
 '(show-paren-match-face ((((class color)) (:background "MediumBlue"))))
 '(cperl-hash-face ((((class color) (background dark)) (:bold nil :italic nil :foreground "Red")))))
