#!/bin/sh

ED=$ZDOTDIR/.emacs.d
  EID=$ZDOTDIR/.emacs.d/init.d
  ELPA=$ZDOTDIR/.emacs.d/elpa
  ES=$ZDOTDIR/.emacs.d/straight
    ESR=$ES/repos
    ESB=$ES/build
LE=$ZDOTDIR/lib/emacs
  LEI=$LE/init
    LEC=$LEI/common
  LEU=$LE/utils
  MAJ=$LE/major-modes
    ORG=$MAJ/org-mode.git
  MIN=$LE/minor-modes
