;; -*- Mode: Emacs-Lisp -*-

(set-face-background 'default "white")

(setq options-file-xemacs-version '(20 4))
  (setq-default case-fold-search t)
  (setq-default overwrite-mode nil)
    (setq-default case-fold-search t)
  (setq-default case-replace t)
    (setq-default zmacs-regions t)
  (setq-default mouse-yank-at-point t)
  (setq-default require-final-newline t)
  (setq-default next-line-add-newlines nil)
  (setq-default teach-extended-commands-p t)
  (setq-default teach-extended-commands-timeout 4)
  (setq-default debug-on-error nil)
  (setq-default debug-on-quit nil)
  (setq-default lpr-switches nil)
  (setq-default ps-print-color-p nil)
  (setq-default ps-paper-type 'letter)
  (setq-default get-frame-for-buffer-default-instance-limit nil)
  (setq-default temp-buffer-show-function 'show-temp-buffer-in-current-frame)
    (setq-default font-lock-auto-fontify t)
  (setq-default font-lock-use-fonts '(or (mono) (grayscale)))
  (setq-default font-lock-use-colors '(color))
  (setq-default font-lock-maximum-decoration 1)
  (setq-default font-lock-maximum-size 256000)
  (setq-default font-lock-mode-enable-list nil)
  (setq-default font-lock-mode-disable-list nil)
  (require 'font-lock)
  (remove-hook 'font-lock-mode-hook 'turn-on-fast-lock)
  (add-hook 'font-lock-mode-hook 'turn-on-lazy-shot)
  (require 'paren)
  (paren-set-mode 'blink-paren)
  (if (featurep 'scrollbar) (progn (add-spec-list-to-specifier scrollbar-width 'nil) (add-spec-list-to-specifier scrollbar-height 'nil)))
  (add-spec-list-to-specifier modeline-shadow-thickness '((global (nil . 2))))
  (setq-default truncate-lines nil)
  (setq-default bar-cursor nil)
  (blink-cursor-mode t)
  (setq-default buffers-menu-max-size 25)
  (setq-default complex-buffers-menu-p nil)
  (setq-default buffers-menu-sort-function nil)
  (setq-default buffers-menu-grouping-function nil)
  (setq-default buffers-menu-submenus-for-groups-p nil)
  (setq-default font-menu-ignore-scaled-fonts t)
  (setq-default font-menu-this-frame-only-p nil)
  (if (featurep 'toolbar) (progn (set-default-toolbar-position 'top) (add-spec-list-to-specifier default-toolbar-visible-p 'nil) (add-spec-list-to-specifier toolbar-buttons-captioned-p 'nil)))
  (setq-default mouse-avoidance-mode nil)
  (setq-default browse-url-browser-function 'browse-url-netscape)
      
